[package]
name = "iroh-addr-index-proto"
description = "Wire protocol for an opaque UDP address index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
readme = "README.md"

[dependencies]
postcard.workspace = true
serde.workspace = true

[lints]
workspace = true
