[workspace]
members = [
    "iroh-addr-index-proto",
    "iroh-addr-index",
    "iroh-mainline-endpoint-discovery",
    "iroh-local-gateway",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
authors = ["Rüdiger Klaehn <rklaehn@protonmail.com>"]

[workspace.dependencies]
anyhow = "1"
blake3 = "1"
clap = { version = "4", features = ["derive", "env"] }
iroh = "1.1"
iroh-base = { version = "1.1", features = ["key"] }
iroh-blobs = "0.103"
n0-future = "0.3"
n0-mainline = { version = "0.6", git = "https://github.com/n0-computer/n0-mainline.git", branch = "addr-index-datagrams" }
postcard = { version = "1", features = ["alloc", "use-std"] }
rand = "0.10"
serde = { version = "1", features = ["derive"] }
sha1_smol = "1"
tokio = { version = "1", features = ["sync", "macros", "rt", "rt-multi-thread", "signal", "time", "net"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
