//! Wire types for an opaque UDP address index.
//!
//! A server maps the public IPv4 socket from which it receives an authorized
//! put to application-defined bytes. Write tokens prove return-routability to
//! that socket without requiring per-token server state.

#![deny(missing_docs, rustdoc::broken_intra_doc_links)]

use std::net::SocketAddrV4;

use serde::{Deserialize, Serialize};

/// Wire discriminator for address-index datagrams.
///
/// The leading zero makes these packets unambiguously distinct from Mainline
/// KRPC messages, which are bencoded dictionaries and therefore start with
/// `b'd'`.
pub const MAGIC: &[u8; 8] = b"\0addridx";

/// Server rendezvous infohash: SHA-1 of `iroh-addr-index servers v1`.
/// Servers announce their implied source port; clients discover them with get_peers.
pub const RENDEZVOUS_INFOHASH: [u8; 20] = [
    184, 108, 61, 145, 14, 26, 103, 236, 155, 168, 166, 154, 149, 189, 127, 139, 8, 190, 146, 59,
];

/// Maximum UDP payload, chosen to avoid IP fragmentation.
pub const MAX_DGRAM: usize = 1200;

/// Maximum opaque value length that always leaves room for protocol framing.
pub const MAX_VALUE_LEN: usize = 1024;

/// Client-generated identifier used to match UDP replies to requests.
pub type TransactionId = u64;

/// Stateless write token generated by a server.
pub type Token = [u8; 16];

/// Everything that goes on the wire, in one postcard tag space.
///
/// Both directions share a namespace, so a request cannot be read as a
/// response. Without that, every request decodes as some response: a `Get`
/// padded to [`MAX_DGRAM`] reads as a `Value` with no value, which lets an
/// off-path attacker answer a client's lookup with "no record" by guessing a
/// transaction id.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Proto {
    /// Sent by a client.
    Request(Request),
    /// Sent by a server.
    Response(Response),
}

impl Proto {
    /// Encode [`MAGIC`] and the postcard body into a datagram buffer.
    /// Get requests are padded with trailing zeros to exactly [`MAX_DGRAM`]
    /// bytes, so no response can be larger than the request that caused it.
    pub fn encode<'a>(&self, buf: &'a mut [u8; MAX_DGRAM]) -> Result<&'a [u8], postcard::Error> {
        buf[..MAGIC.len()].copy_from_slice(MAGIC);
        let len = MAGIC.len() + postcard::to_slice(self, &mut buf[MAGIC.len()..])?.len();
        if self.is_padded() {
            buf[len..].fill(0);
            Ok(buf)
        } else {
            Ok(&buf[..len])
        }
    }

    /// Decode a framed datagram, rejecting packets without the discriminator.
    /// Rejects oversized packets and get requests that are not padded.
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() > MAX_DGRAM {
            return None;
        }
        let body = data.strip_prefix(MAGIC)?;
        let value: Self = postcard::from_bytes(body).ok()?;
        (!value.is_padded() || data.len() == MAX_DGRAM).then_some(value)
    }

    /// Whether this datagram is padded to a full [`MAX_DGRAM`] buffer.
    fn is_padded(&self) -> bool {
        matches!(self, Self::Request(Request::V1(RequestV1::Get { .. })))
    }
}

/// Versioned postcard request. Unknown versions are dropped by receivers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Request {
    /// Current request body.
    V1(RequestV1),
}

/// Version-one request body.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RequestV1 {
    /// Ask the server to observe this packet's public IPv4 socket and issue a write token.
    Prepare {
        /// Identifier echoed in the response.
        tx: TransactionId,
        /// Makes the challenge at least as large as its response.
        padding: [u8; 24],
    },
    /// Store opaque bytes under this packet's observed source socket.
    Put {
        /// Identifier echoed in the response.
        tx: TransactionId,
        /// Token previously issued to this source socket.
        token: Token,
        /// Application-defined bytes.
        value: Vec<u8>,
    },
    /// Read the value stored for an exact public IPv4 socket.
    /// The framed datagram must be padded to [`MAX_DGRAM`] bytes; receivers
    /// ignore the padding after the postcard payload.
    Get {
        /// Identifier echoed in the response.
        tx: TransactionId,
        /// Address-index key.
        addr: SocketAddrV4,
    },
}

/// Versioned postcard response. Unknown versions are dropped by clients.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Response {
    /// Current response body.
    V1(ResponseV1),
}

/// Version-one response body.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseV1 {
    /// Result of [`RequestV1::Prepare`].
    Prepared {
        /// Identifier copied from the request.
        tx: TransactionId,
        /// Public IPv4 socket observed by the server.
        addr: SocketAddrV4,
        /// Stateless token bound to `addr`.
        token: Token,
    },
    /// Confirmation that a value was accepted.
    Stored {
        /// Identifier copied from the put.
        tx: TransactionId,
        /// Address under which the value was stored.
        addr: SocketAddrV4,
    },
    /// Result of [`RequestV1::Get`].
    Value {
        /// Identifier copied from the request.
        tx: TransactionId,
        /// Queried address.
        addr: SocketAddrV4,
        /// Opaque bytes, or `None` when no live value exists.
        value: Option<Vec<u8>>,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    fn request(request: RequestV1) -> Proto {
        Proto::Request(Request::V1(request))
    }

    fn response(response: ResponseV1) -> Proto {
        Proto::Response(Response::V1(response))
    }

    #[test]
    fn maximum_packets_fit() {
        let put = request(RequestV1::Put {
            tx: u64::MAX,
            token: [0xff; 16],
            value: vec![0xff; MAX_VALUE_LEN],
        });
        let value = response(ResponseV1::Value {
            tx: u64::MAX,
            addr: "255.255.255.255:65535".parse().unwrap(),
            value: Some(vec![0xff; MAX_VALUE_LEN]),
        });
        assert!(put.encode(&mut [0; MAX_DGRAM]).is_ok());
        assert!(value.encode(&mut [0; MAX_DGRAM]).is_ok());
    }

    #[test]
    fn requests_and_responses_do_not_decode_as_each_other() {
        let addr = "203.0.113.1:1234".parse().unwrap();
        let packets = [
            request(RequestV1::Prepare {
                tx: 7,
                padding: [0; 24],
            }),
            request(RequestV1::Put {
                tx: 8,
                token: [1; 16],
                value: vec![9; 40],
            }),
            request(RequestV1::Get { tx: 9, addr }),
            response(ResponseV1::Prepared {
                tx: 7,
                addr,
                token: [1; 16],
            }),
            response(ResponseV1::Stored { tx: 8, addr }),
            response(ResponseV1::Value {
                tx: 9,
                addr,
                value: Some(vec![7; 900]),
            }),
        ];
        let mut buf = [0; MAX_DGRAM];
        for packet in &packets {
            let bytes = packet.encode(&mut buf).unwrap().to_vec();
            let decoded = Proto::decode(&bytes);
            assert_eq!(decoded.as_ref(), Some(packet));
            // The direction a packet decodes to is the one it was sent as.
            assert_eq!(
                matches!(decoded, Some(Proto::Request(_))),
                matches!(packet, Proto::Request(_)),
                "{packet:?}"
            );
        }
    }

    #[test]
    fn get_padding_is_required_and_bounds_response_size() {
        for tx in [0, u64::MAX] {
            let addr = "255.255.255.255:65535".parse().unwrap();
            let get = request(RequestV1::Get { tx, addr });
            let mut buf = [0xff; MAX_DGRAM];
            let bytes = get.encode(&mut buf).unwrap();
            assert_eq!(bytes.len(), MAX_DGRAM);
            assert_eq!(Proto::decode(bytes), Some(get.clone()));
            let body = &bytes[MAGIC.len()..];
            let (_, padding) = postcard::take_from_bytes::<Proto>(body).unwrap();
            assert!(!padding.is_empty());
            assert!(padding.iter().all(|byte| *byte == 0));
            for len in 0..MAX_DGRAM {
                assert!(Proto::decode(&bytes[..len]).is_none());
            }
            let mut oversized = bytes.to_vec();
            oversized.push(0);
            assert!(Proto::decode(&oversized).is_none());
            let value = response(ResponseV1::Value {
                tx,
                addr,
                value: Some(vec![0xff; MAX_VALUE_LEN]),
            });
            assert!(value.encode(&mut [0; MAX_DGRAM]).unwrap().len() <= bytes.len());
        }
    }

    #[test]
    fn prepare_does_not_amplify() {
        let prepare = request(RequestV1::Prepare {
            tx: u64::MAX,
            padding: [0; 24],
        });
        let prepared = response(ResponseV1::Prepared {
            tx: u64::MAX,
            addr: "255.255.255.255:65535".parse().unwrap(),
            token: [0xff; 16],
        });
        let prepare_len = prepare.encode(&mut [0; MAX_DGRAM]).unwrap().len();
        let prepared_len = prepared.encode(&mut [0; MAX_DGRAM]).unwrap().len();
        assert!(prepared_len <= prepare_len);
    }

    #[test]
    fn garbage_is_rejected() {
        assert!(Proto::decode(b"xxxx").is_none());
        assert!(Proto::decode(&[]).is_none());
    }

    #[test]
    fn framing_cannot_be_krpc() {
        let prepare = request(RequestV1::Prepare {
            tx: 0,
            padding: [0; 24],
        });
        let mut buf = [0; MAX_DGRAM];
        let encoded = prepare.encode(&mut buf).unwrap();
        assert!(encoded.starts_with(MAGIC));
        assert_ne!(encoded[0], b'd');
        assert_eq!(Proto::decode(encoded).unwrap(), prepare);
    }
}
