//! Wire types for an opaque UDP address index.
//!
//! A replica maps the public IPv4 socket from which it receives an authorized
//! put to application-defined bytes. Write tokens prove return-routability to
//! that socket without requiring per-token server state.

#![deny(missing_docs, rustdoc::broken_intra_doc_links)]

use std::net::SocketAddrV4;

use serde::{Deserialize, Serialize};

/// Wire discriminator for address-index datagrams.
///
/// The leading zero makes these packets unambiguously distinct from Mainline
/// KRPC messages, which are bencoded dictionaries and therefore start with
/// `b'd'`.
pub const MAGIC: &[u8; 8] = b"\0addridx";

/// Maximum UDP payload, chosen to avoid IP fragmentation.
pub const MAX_DGRAM: usize = 1200;

/// Maximum opaque value length that always leaves room for protocol framing.
pub const MAX_VALUE_LEN: usize = 1024;

/// Client-generated identifier used to match UDP replies to requests.
pub type TransactionId = u64;

/// Stateless write token generated by a replica.
pub type Token = [u8; 16];

/// Versioned postcard request. Unknown versions are dropped by receivers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Request {
    /// Current request body.
    V1(RequestV1),
}

impl Request {
    /// Encode a framed request into a maximum-sized datagram buffer.
    /// Get requests are padded with trailing zeros to exactly [`MAX_DGRAM`] bytes.
    pub fn encode<'a>(&self, buf: &'a mut [u8; MAX_DGRAM]) -> Result<&'a [u8], postcard::Error> {
        let len = encode(self, buf)?.len();
        if matches!(self, Self::V1(RequestV1::Get { .. })) {
            buf[len..].fill(0);
            Ok(buf)
        } else {
            Ok(&buf[..len])
        }
    }

    /// Decode a framed request, rejecting packets without the discriminator.
    /// Rejects oversized packets and get requests shorter than [`MAX_DGRAM`].
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() > MAX_DGRAM {
            return None;
        }
        let request = decode(data)?;
        if matches!(request, Self::V1(RequestV1::Get { .. })) && data.len() != MAX_DGRAM {
            return None;
        }
        Some(request)
    }
}

/// Version-one request body.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RequestV1 {
    /// Ask the replica to observe this packet's public IPv4 socket and issue a write token.
    Prepare {
        /// Identifier echoed in the response.
        tx: TransactionId,
        /// Makes the challenge at least as large as its response.
        padding: [u8; 24],
    },
    /// Store opaque bytes under this packet's observed source socket.
    Put {
        /// Identifier echoed in the response.
        tx: TransactionId,
        /// Token previously issued to this source socket.
        token: Token,
        /// Application-defined bytes.
        value: Vec<u8>,
    },
    /// Read the value stored for an exact public IPv4 socket.
    /// The framed datagram must be padded to [`MAX_DGRAM`] bytes; receivers
    /// ignore the padding after the postcard payload.
    Get {
        /// Identifier echoed in the response.
        tx: TransactionId,
        /// Address-index key.
        addr: SocketAddrV4,
    },
}

/// Versioned postcard response. Unknown versions are dropped by clients.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Response {
    /// Current response body.
    V1(ResponseV1),
}

impl Response {
    /// Encode a framed response into a maximum-sized datagram buffer.
    pub fn encode<'a>(&self, buf: &'a mut [u8; MAX_DGRAM]) -> Result<&'a [u8], postcard::Error> {
        encode(self, buf)
    }

    /// Decode a framed response, rejecting packets without the discriminator.
    pub fn decode(data: &[u8]) -> Option<Self> {
        decode(data)
    }
}

/// Version-one response body.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseV1 {
    /// Result of [`RequestV1::Prepare`].
    Prepared {
        /// Identifier copied from the request.
        tx: TransactionId,
        /// Public IPv4 socket observed by the replica.
        addr: SocketAddrV4,
        /// Stateless token bound to `addr`.
        token: Token,
    },
    /// Confirmation that a value was accepted.
    Stored {
        /// Identifier copied from the put.
        tx: TransactionId,
        /// Address under which the value was stored.
        addr: SocketAddrV4,
    },
    /// Result of [`RequestV1::Get`].
    Value {
        /// Identifier copied from the request.
        tx: TransactionId,
        /// Queried address.
        addr: SocketAddrV4,
        /// Opaque bytes, or `None` when no live value exists.
        value: Option<Vec<u8>>,
    },
}

fn encode<'a, T: Serialize>(
    value: &T,
    buf: &'a mut [u8; MAX_DGRAM],
) -> Result<&'a [u8], postcard::Error> {
    buf[..MAGIC.len()].copy_from_slice(MAGIC);
    let payload = postcard::to_slice(value, &mut buf[MAGIC.len()..])?;
    let len = MAGIC.len() + payload.len();
    Ok(&buf[..len])
}

fn decode<'a, T: Deserialize<'a>>(data: &'a [u8]) -> Option<T> {
    let payload = data.strip_prefix(MAGIC)?;
    postcard::from_bytes(payload).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maximum_packets_fit() {
        let put = Request::V1(RequestV1::Put {
            tx: u64::MAX,
            token: [0xff; 16],
            value: vec![0xff; MAX_VALUE_LEN],
        });
        let value = Response::V1(ResponseV1::Value {
            tx: u64::MAX,
            addr: "255.255.255.255:65535".parse().unwrap(),
            value: Some(vec![0xff; MAX_VALUE_LEN]),
        });
        assert!(put.encode(&mut [0; MAX_DGRAM]).is_ok());
        assert!(value.encode(&mut [0; MAX_DGRAM]).is_ok());
    }

    #[test]
    fn get_padding_is_required_and_bounds_response_size() {
        for tx in [0, u64::MAX] {
            let addr = "255.255.255.255:65535".parse().unwrap();
            let request = Request::V1(RequestV1::Get { tx, addr });
            let mut buf = [0xff; MAX_DGRAM];
            let bytes = request.encode(&mut buf).unwrap();
            assert_eq!(bytes.len(), MAX_DGRAM);
            assert_eq!(Request::decode(bytes), Some(request.clone()));
            let (_, padding) = postcard::take_from_bytes::<Request>(&bytes[MAGIC.len()..]).unwrap();
            assert!(!padding.is_empty());
            assert!(padding.iter().all(|byte| *byte == 0));
            for len in 0..MAX_DGRAM {
                assert!(Request::decode(&bytes[..len]).is_none());
            }
            let mut oversized = bytes.to_vec();
            oversized.push(0);
            assert!(Request::decode(&oversized).is_none());
            let response = Response::V1(ResponseV1::Value {
                tx,
                addr,
                value: Some(vec![0xff; MAX_VALUE_LEN]),
            });
            assert!(response.encode(&mut [0; MAX_DGRAM]).unwrap().len() <= bytes.len());
        }
    }

    #[test]
    fn prepare_does_not_amplify() {
        let prepare = Request::V1(RequestV1::Prepare {
            tx: u64::MAX,
            padding: [0; 24],
        });
        let prepared = Response::V1(ResponseV1::Prepared {
            tx: u64::MAX,
            addr: "255.255.255.255:65535".parse().unwrap(),
            token: [0xff; 16],
        });
        let prepare_len = prepare.encode(&mut [0; MAX_DGRAM]).unwrap().len();
        let prepared_len = prepared.encode(&mut [0; MAX_DGRAM]).unwrap().len();
        assert!(prepared_len <= prepare_len);
    }

    #[test]
    fn garbage_is_rejected() {
        assert!(Request::decode(b"xxxx").is_none());
        assert!(Request::decode(&[]).is_none());
    }

    #[test]
    fn framing_cannot_be_krpc() {
        let request = Request::V1(RequestV1::Prepare {
            tx: 0,
            padding: [0; 24],
        });
        let mut buf = [0; MAX_DGRAM];
        let encoded = request.encode(&mut buf).unwrap();
        assert!(encoded.starts_with(MAGIC));
        assert_ne!(encoded[0], b'd');
        assert_eq!(Request::decode(encoded).unwrap(), request);
    }
}
