[package]
name = "iroh-mainline-endpoint-discovery"
description = "Publish and discover iroh endpoints through Mainline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
readme = "../README.md"
keywords = ["iroh", "p2p", "dht", "mainline", "discovery"]
categories = ["network-programming"]

[dependencies]
async-stream = "0.3"
blake3.workspace = true
clap.workspace = true
iroh-base.workspace = true
udp-address-records-proto = { version = "0.1.0", path = "../udp-address-records-proto" }
n0-error = "1.0.1"
n0-future.workspace = true
n0-mainline.workspace = true
postcard.workspace = true
serde.workspace = true
sha1_smol.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zeroize = "1"

[dev-dependencies]
iroh.workspace = true
iroh-blobs.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }

[lints]
workspace = true
